#!/usr/bin/env bash
#
# Synapse one-click installer (Linux / macOS; re-execs PowerShell on Windows).
#
# WHAT: bootstraps a Node.js runtime that satisfies @synapse package engines,
#       installs @synapse/device-runtime or @synapse/remote-agent-daemon from
#       the private registry, then pairs the device / starts the daemon.
# WHY:  the @synapse npm packages need Node + a configured @synapse:registry
#       BEFORE they can run; this script supplies that bootstrap step.
#
# This file is the canonical source. The API serves it at
#   GET /api/v1/install.sh
# after substituting the @@SYNAPSE_*@@ placeholders with the live instance
# values. The Node sha256 manifest between the SYNAPSE_NODE_MANIFEST markers is
# generated by scripts/installer/generate-node-manifest.mjs.
#
# SECURITY: Node binaries are downloaded to a file and verified against the
# embedded sha256 (sourced from canonical nodejs.org, never from a mirror)
# before use. The whole body is wrapped in __main()/__main "$@" so a truncated
# download never executes a partial script.
#
# bash 3.2 compatible (macOS /bin/bash): no associative arrays, no mapfile, no
# ${var,,}. Knobs are SYNAPSE_*-prefixed; state-changing ops go through run()
# so SYNAPSE_INSTALL_DRY_RUN / --dry-run yields a hermetic, testable trace.

set -euo pipefail

# --- temp cleanup registry -------------------------------------------------
# A single EXIT trap removes every registered temp path. Functions must NOT
# put their own temp dirs in a `local` referenced by a trap: the trap runs in
# global scope at process exit, where a function-local is out of scope and (under
# set -u) would be an "unbound variable". Register via track_tmp instead.
SYNAPSE_TMP_PATHS=""
track_tmp() { SYNAPSE_TMP_PATHS="$SYNAPSE_TMP_PATHS $1"; }
# shellcheck disable=SC2064
trap 'for _p in $SYNAPSE_TMP_PATHS; do rm -rf "$_p" 2>/dev/null || true; done' EXIT

# --- server-rendered placeholders (substituted by the API route) ----------
# The API route replaces each quoted '@@...@@' token with a fully shell-quoted
# literal (e.g. 'https://host/'). The quotes here keep this a valid bash
# assignment when the script is run raw (not via the route); in that case the
# tokens stay literal and are treated as unset by the "@@"*"@@" guard below.
SYNAPSE_RENDERED_SERVER_URL='@@SYNAPSE_SERVER_URL@@'
SYNAPSE_RENDERED_PRIVATE_REGISTRY='@@SYNAPSE_NPM_REGISTRY@@'
# sha256 of the rendered install.ps1, injected so the Git-Bash → PowerShell
# re-exec path can verify the downloaded ps1 before running it.
SYNAPSE_RENDERED_PS1_SHA256='@@SYNAPSE_PS1_SHA256@@'

# >>> SYNAPSE_NODE_MANIFEST (generated — do not edit by hand) >>>
INSTALLER_NODE_VERSION="24.16.0"
node_artifact_sha256() {
  case "$1" in
    linux-x64) printf '%s' "2faf6a387e9b62b888e21c54f01249fb27537ffecf1842f29f4c919d0a59a0ff" ;;
    linux-arm64) printf '%s' "589f5b6dd4fcfee4dfda73013903c966abaa8abd93dbc9d436544e472b4f0e74" ;;
    darwin-x64) printf '%s' "298b4c7b3cb80765c8703e42b90324a4ece3b6634947b89e769c3c980ab55185" ;;
    darwin-arm64) printf '%s' "39189dab4eeb15706c424af0ac08a3044c9e48f7db12a7d77f6b7aafc7dd5df6" ;;
    win-x64) printf '%s' "edaca9bd58ec8e92037dac4e877d52f6b8f430b81c18b57e264b4e2fb111cd56" ;;
    win-arm64) printf '%s' "14834611d4c6b3c06054e7007732b90474c16e0b32f395e05b55a571ef71c6d2" ;;
    *) return 1 ;;
  esac
}
# <<< SYNAPSE_NODE_MANIFEST <<<

__main() {
  # ---- logging (stderr, so stdout stays clean) --------------------------
  log() { echo "[synapse-install] $*" >&2; }
  warn() { echo "[synapse-install] WARN: $*" >&2; }
  die() { echo "[synapse-install] ERROR: $*" >&2; exit 1; }

  # ---- dry-run wrapper --------------------------------------------------
  # In dry-run, every state-changing command is echoed (prefixed DRYRUN) to
  # stdout instead of executed. Read-only probes still run.
  DRY_RUN="${SYNAPSE_INSTALL_DRY_RUN:-false}"
  run() {
    if [ "$DRY_RUN" = "true" ]; then
      echo "DRYRUN: $*"
    else
      "$@"
    fi
  }

  # ---- defaults / config ------------------------------------------------
  SYNAPSE_HOME="${SYNAPSE_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/synapse}"
  NODE_PREFIX_BASE="$SYNAPSE_HOME/node"
  NPM_GLOBAL_PREFIX="$SYNAPSE_HOME/npm-global"
  MANAGED_NPMRC="$SYNAPSE_HOME/npmrc"
  BOOTSTRAPPED_NODE_BIN=""  # set by bootstrap_node when we install our own Node
  RC_MARKER_BEGIN="# >>> synapse installer >>>"
  RC_MARKER_END="# <<< synapse installer <<<"

  TARGET=""
  SERVER="${SYNAPSE_SERVER_ORIGIN:-$SYNAPSE_RENDERED_SERVER_URL}"
  PAIRING_CODE=""
  API_KEY=""
  REGION="${SYNAPSE_REGION:-}"
  MIRROR_FLAG=""               # explicit --mirror (key or custom URL)
  TOOLCHAIN_MIRROR_FLAG=""     # explicit --toolchain-mirror (P5 key only)
  NO_MODIFY_PATH=false
  WRITE_USER_NPMRC=false
  PREFER_PRIVATE_CACHE=false
  PRIVATE_REGISTRY="${SYNAPSE_PRIVATE_NPM_REGISTRY:-$SYNAPSE_RENDERED_PRIVATE_REGISTRY}"

  parse_args "$@"

  # An unsubstituted placeholder means the script was run raw (not via the
  # API route). Treat as unset.
  case "$SERVER" in "@@"*"@@") SERVER="" ;; esac
  case "$PRIVATE_REGISTRY" in "@@"*"@@") PRIVATE_REGISTRY="" ;; esac
  case "$SYNAPSE_RENDERED_PS1_SHA256" in "@@"*"@@") SYNAPSE_RENDERED_PS1_SHA256="" ;; esac

  [ -n "$TARGET" ] || die "--target <device|daemon> is required"
  case "$TARGET" in
    device|daemon) : ;;
    *) die "--target must be 'device' or 'daemon' (got '$TARGET')" ;;
  esac

  detect_platform                 # sets OS, ARCH, ARTIFACT_KEY (or re-execs Windows)
  [ "$OS" = "linux" ] && detect_libc

  detect_region                   # sets REGION (cn|intl) if not already set
  resolve_toolchain_mirror        # sets NODE_MIRROR_BASE, NODE_MIRROR_KEY, P5_MIRROR

  ensure_node                     # sets NODE_BIN / NPM_BIN (bootstrap if needed)
  configure_npmrc                 # writes managed npmrc (+ user npmrc if asked)
  export_toolchain_mirror         # P5 SYNAPSE_DEVICE_TOOLCHAIN_MIRROR
  install_synapse_pkg             # npm i -g into managed prefix
  post_install                    # run_pair / run_daemon + next steps

  log "Done."
}

# ---------------------------------------------------------------------------
parse_args() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --target) TARGET="${2:-}"; shift 2 ;;
      --target=*) TARGET="${1#*=}"; shift ;;
      --server) SERVER="${2:-}"; shift 2 ;;
      --server=*) SERVER="${1#*=}"; shift ;;
      --code) PAIRING_CODE="${2:-}"; shift 2 ;;
      --code=*) PAIRING_CODE="${1#*=}"; shift ;;
      --api-key) API_KEY="${2:-}"; shift 2 ;;
      --api-key=*) API_KEY="${1#*=}"; shift ;;
      --region) REGION="${2:-}"; shift 2 ;;
      --region=*) REGION="${1#*=}"; shift ;;
      --mirror) MIRROR_FLAG="${2:-}"; shift 2 ;;
      --mirror=*) MIRROR_FLAG="${1#*=}"; shift ;;
      --toolchain-mirror) TOOLCHAIN_MIRROR_FLAG="${2:-}"; shift 2 ;;
      --toolchain-mirror=*) TOOLCHAIN_MIRROR_FLAG="${1#*=}"; shift ;;
      --no-modify-path) NO_MODIFY_PATH=true; shift ;;
      --write-user-npmrc) WRITE_USER_NPMRC=true; shift ;;
      --prefer-private-cache) PREFER_PRIVATE_CACHE=true; shift ;;
      --dry-run) DRY_RUN=true; shift ;;
      -h|--help) usage; exit 0 ;;
      *) die "unknown argument: $1 (try --help)" ;;
    esac
  done
}

usage() {
  cat >&2 <<'EOF'
Synapse installer
  --target device|daemon     (required) what to install
  --server <url>             Synapse server origin
  --code <pairing-code>      device: auto-run pairing after install
  --api-key <key>            daemon: api key to start with
  --region cn|intl           override geo detection
  --mirror <key|url>         Node download source (ustc|huawei|tencent|aliyun|npmmirror|nodejs|<url>)
  --toolchain-mirror <key>   P5 device toolchain mirror (ustc|huawei|tencent|aliyun|npmmirror)
  --no-modify-path           do not edit shell profiles / user PATH (overrides --write-user-npmrc)
  --write-user-npmrc         also write @synapse:registry into ~/.npmrc
  --prefer-private-cache     route third-party deps through the private registry too
  --dry-run                  print actions without executing
EOF
}

# ---------------------------------------------------------------------------
# Maps a mirror key to its Node-dist base URL. Returns 1 for unknown keys.
# This table is the single source of truth shared conceptually with the P5
# TRUSTED_SOURCES entries (mirror base paths differ per host).
mirror_base_for_key() {
  case "$1" in
    ustc) printf '%s' "https://mirrors.ustc.edu.cn/node/" ;;
    huawei) printf '%s' "https://mirrors.huaweicloud.com/nodejs/" ;;
    tencent) printf '%s' "https://mirrors.cloud.tencent.com/nodejs-release/" ;;
    aliyun) printf '%s' "https://mirrors.aliyun.com/nodejs-release/" ;;
    npmmirror) printf '%s' "https://cdn.npmmirror.com/binaries/node/" ;;
    nodejs) printf '%s' "https://nodejs.org/dist/" ;;
    *) return 1 ;;
  esac
}

# True if the key is a valid P5 toolchain-mirror key (excludes nodejs/custom).
is_p5_mirror_key() {
  case "$1" in
    ustc|huawei|tencent|aliyun|npmmirror) return 0 ;;
    *) return 1 ;;
  esac
}

# ---------------------------------------------------------------------------
detect_platform() {
  local uname_s uname_m
  uname_s="$(uname -s 2>/dev/null || echo unknown)"
  uname_m="$(uname -m 2>/dev/null || echo unknown)"

  case "$uname_s" in
    MINGW*|MSYS*|CYGWIN*|Windows_NT) reexec_windows; exit $? ;;
    Linux) OS="linux" ;;
    Darwin) OS="darwin" ;;
    *) die "unsupported OS: $uname_s" ;;
  esac

  case "$uname_m" in
    x86_64|amd64|x64) ARCH="x64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) die "unsupported architecture: $uname_m" ;;
  esac

  # macOS under Rosetta reports x86_64; correct to arm64 on real Apple silicon.
  if [ "$OS" = "darwin" ] && [ "$ARCH" = "x64" ]; then
    if [ "$(sysctl -n sysctl.proc_translated 2>/dev/null || echo 0)" = "1" ]; then
      ARCH="arm64"
    fi
  fi

  ARTIFACT_KEY="$OS-$ARCH"
  log "platform: $ARTIFACT_KEY"
}

# Git-Bash / MSYS path: download install.ps1, verify against embedded shaPs1,
# translate ALL flags, then hand off to PowerShell. Dropping flags here would
# turn --dry-run into a real install or silently defeat --no-modify-path.
reexec_windows() {
  command -v powershell.exe >/dev/null 2>&1 || command -v powershell >/dev/null 2>&1 \
    || die "Windows shell detected but PowerShell not found; run the Windows install command instead."
  [ -n "$SYNAPSE_RENDERED_PS1_SHA256" ] \
    || die "no embedded install.ps1 sha256; fetch the installer from the Synapse server, or use the Windows command."
  [ -n "$SERVER" ] || die "--server is required for the Windows re-exec path"

  local ps_url tmp_ps got
  ps_url="${SERVER%/}/api/v1/install.ps1"
  tmp_ps="$(mktemp -t synapse-install.XXXXXX.ps1)"
  track_tmp "$tmp_ps"
  fetch_to_file "$ps_url" "$tmp_ps"
  got="$(sha256_of "$tmp_ps")"
  [ "$got" = "$SYNAPSE_RENDERED_PS1_SHA256" ] \
    || die "install.ps1 sha256 mismatch (expected $SYNAPSE_RENDERED_PS1_SHA256, got $got)"

  # Translate the full flag surface to PowerShell parameters.
  local ps_args
  ps_args="-Target $(ps_quote "$TARGET")"
  [ -n "$SERVER" ] && ps_args="$ps_args -Server $(ps_quote "$SERVER")"
  [ -n "$PAIRING_CODE" ] && ps_args="$ps_args -Code $(ps_quote "$PAIRING_CODE")"
  [ -n "$API_KEY" ] && ps_args="$ps_args -ApiKey $(ps_quote "$API_KEY")"
  [ -n "$REGION" ] && ps_args="$ps_args -Region $(ps_quote "$REGION")"
  [ -n "$MIRROR_FLAG" ] && ps_args="$ps_args -Mirror $(ps_quote "$MIRROR_FLAG")"
  [ -n "$TOOLCHAIN_MIRROR_FLAG" ] && ps_args="$ps_args -ToolchainMirror $(ps_quote "$TOOLCHAIN_MIRROR_FLAG")"
  [ "$NO_MODIFY_PATH" = "true" ] && ps_args="$ps_args -NoModifyPath"
  [ "$WRITE_USER_NPMRC" = "true" ] && ps_args="$ps_args -WriteUserNpmrc"
  [ "$PREFER_PRIVATE_CACHE" = "true" ] && ps_args="$ps_args -PreferPrivateCache"
  [ "$DRY_RUN" = "true" ] && ps_args="$ps_args -DryRun"

  local pwsh_bin
  if command -v powershell.exe >/dev/null 2>&1; then pwsh_bin="powershell.exe"; else pwsh_bin="powershell"; fi
  log "handing off to PowerShell: $tmp_ps"
  run "$pwsh_bin" -ExecutionPolicy Bypass -NoProfile -File "$tmp_ps" $ps_args
}

# PowerShell single-quote escaping ('' escapes an embedded quote).
ps_quote() {
  local s="$1"
  s="$(printf '%s' "$s" | sed "s/'/''/g")"
  printf "'%s'" "$s"
}

detect_libc() {
  # Official nodejs.org linux tarballs are glibc builds; refuse on musl/Alpine
  # rather than install a binary that cannot run.
  if [ -f /etc/alpine-release ]; then
    die "musl libc (Alpine) detected — official Node tarballs are glibc-only. Install Node via your package manager (apk add nodejs npm) and re-run."
  fi
  if command -v ldd >/dev/null 2>&1; then
    if ldd --version 2>&1 | grep -qi musl; then
      die "musl libc detected — official Node tarballs are glibc-only. Install Node via your package manager and re-run."
    fi
  fi
}

# ---------------------------------------------------------------------------
# True if $1 (e.g. v22.12.0 or 22.12.0) satisfies @synapse engines:
#   ^20.19.0 || ^22.12.0 || >=23
node_engines_ok() {
  local v="${1#v}"
  local major minor patch
  major="${v%%.*}"; v="${v#*.}"
  minor="${v%%.*}"; v="${v#*.}"
  patch="${v%%.*}"
  case "$major$minor$patch" in *[!0-9]*|"") return 1 ;; esac
  if [ "$major" -ge 23 ]; then return 0; fi
  if [ "$major" -eq 22 ] && [ "$minor" -ge 12 ]; then return 0; fi
  if [ "$major" -eq 20 ]; then
    if [ "$minor" -gt 19 ]; then return 0; fi
    if [ "$minor" -eq 19 ] && [ "$patch" -ge 0 ]; then return 0; fi
  fi
  return 1
}

# ---------------------------------------------------------------------------
detect_region() {
  if [ -n "$REGION" ]; then
    case "$REGION" in
      cn|intl) log "region: $REGION (explicit)"; return ;;
      *) die "--region must be 'cn' or 'intl' (got '$REGION')" ;;
    esac
  fi

  # Primary signal: TLS-handshake latency race, domestic vs international.
  # Bounded so we never hang; default to intl on any uncertainty.
  local cn_ms intl_ms
  cn_ms="$(tls_connect_ms "https://registry.npmmirror.com/")"
  intl_ms="$(tls_connect_ms "https://registry.npmjs.org/")"

  if [ "$cn_ms" -ge 0 ] && [ "$intl_ms" -lt 0 ]; then
    REGION="cn"; log "region: cn (intl unreachable, domestic ok)"; return
  fi
  if [ "$cn_ms" -ge 0 ] && [ "$intl_ms" -ge 0 ]; then
    # domestic must be clearly faster (>=1.5x) to claim cn
    if [ "$((cn_ms * 3))" -le "$((intl_ms * 2))" ]; then
      REGION="cn"; log "region: cn (latency race ${cn_ms}ms vs ${intl_ms}ms)"; return
    fi
    REGION="intl"; log "region: intl (latency race ${cn_ms}ms vs ${intl_ms}ms)"; return
  fi

  # Network race inconclusive: weak tiebreak via timezone/locale, else intl.
  local tz="${TZ:-}"
  [ -z "$tz" ] && [ -r /etc/timezone ] && tz="$(cat /etc/timezone 2>/dev/null || true)"
  case "$tz" in
    Asia/Shanghai|Asia/Urumqi|Asia/Chongqing)
      REGION="cn"; log "region: cn (timezone tiebreak, network inconclusive)"; return ;;
  esac
  case "${LANG:-}${LC_ALL:-}" in
    *zh_CN*) REGION="cn"; log "region: cn (locale tiebreak)"; return ;;
  esac
  REGION="intl"; log "region: intl (default — network inconclusive)"
}

# Echoes TLS-connect time in ms, or -1 if unreachable. Bounded by max-time.
tls_connect_ms() {
  local url="$1" t
  if ! command -v curl >/dev/null 2>&1; then echo "-1"; return; fi
  t="$(curl -sS -o /dev/null -m 4 --connect-timeout 2 \
        -w '%{time_appconnect}' "$url" 2>/dev/null || echo "")"
  if [ -z "$t" ] || [ "$t" = "0.000000" ]; then echo "-1"; return; fi
  # seconds.float -> integer ms without bc (bash 3.2 friendly)
  awk -v s="$t" 'BEGIN { printf "%d", s * 1000 }'
}

# ---------------------------------------------------------------------------
# Two-stage mirror resolution (plan §Phase1 resolve_toolchain_mirror):
#   ① NODE_MIRROR  = --mirror > SYNAPSE_NODE_MIRROR > geo-auto > nodejs
#   ② P5_MIRROR    = --toolchain-mirror > NODE_MIRROR(if P5 key) > "" (official)
# Explicit illegal flags die; illegal env values warn + fall back.
resolve_toolchain_mirror() {
  local node_choice="" source="default"

  if [ -n "$MIRROR_FLAG" ]; then
    node_choice="$MIRROR_FLAG"; source="flag"
  elif [ -n "${SYNAPSE_NODE_MIRROR:-}" ]; then
    node_choice="$SYNAPSE_NODE_MIRROR"; source="env"
  elif [ "$REGION" = "cn" ]; then
    node_choice="ustc"; source="geo"   # geo default; reachability cascade below
  else
    node_choice="nodejs"; source="default"
  fi

  # Resolve node_choice -> NODE_MIRROR_BASE + NODE_MIRROR_KEY.
  case "$node_choice" in
    http://*|https://*)
      NODE_MIRROR_BASE="${node_choice%/}/"
      NODE_MIRROR_KEY=""   # custom URL is never a P5 key
      ;;
    *)
      if NODE_MIRROR_BASE="$(mirror_base_for_key "$node_choice")"; then
        NODE_MIRROR_KEY="$node_choice"
      else
        if [ "$source" = "flag" ]; then
          die "--mirror: unknown key '$node_choice' (use ustc|huawei|tencent|aliyun|npmmirror|nodejs or an https:// URL)"
        fi
        warn "ignoring invalid mirror '$node_choice' (from $source); using official nodejs.org"
        NODE_MIRROR_BASE="https://nodejs.org/dist/"; NODE_MIRROR_KEY="nodejs"
      fi
      ;;
  esac

  # nodejs key is the official source — not a P5 mirror key.
  [ "$NODE_MIRROR_KEY" = "nodejs" ] && NODE_MIRROR_KEY=""

  # Stage ②: P5 toolchain mirror.
  P5_MIRROR=""
  if [ -n "$TOOLCHAIN_MIRROR_FLAG" ]; then
    if is_p5_mirror_key "$TOOLCHAIN_MIRROR_FLAG"; then
      P5_MIRROR="$TOOLCHAIN_MIRROR_FLAG"
    else
      die "--toolchain-mirror: must be one of ustc|huawei|tencent|aliyun|npmmirror (got '$TOOLCHAIN_MIRROR_FLAG'); custom URLs are not allowed for the device toolchain"
    fi
  elif [ -n "${SYNAPSE_DEVICE_TOOLCHAIN_MIRROR:-}" ]; then
    if is_p5_mirror_key "$SYNAPSE_DEVICE_TOOLCHAIN_MIRROR"; then
      P5_MIRROR="$SYNAPSE_DEVICE_TOOLCHAIN_MIRROR"
    else
      warn "ignoring invalid SYNAPSE_DEVICE_TOOLCHAIN_MIRROR='$SYNAPSE_DEVICE_TOOLCHAIN_MIRROR'; device toolchain will use official source"
    fi
  elif [ -n "$NODE_MIRROR_KEY" ] && is_p5_mirror_key "$NODE_MIRROR_KEY"; then
    P5_MIRROR="$NODE_MIRROR_KEY"   # inherit the resolved Node mirror key
  fi

  log "node mirror: ${NODE_MIRROR_BASE} (key='${NODE_MIRROR_KEY:-custom/official}'); p5 toolchain mirror: '${P5_MIRROR:-official}'"
}

# ---------------------------------------------------------------------------
ensure_node() {
  # Fast path: a system Node that already satisfies engines.
  if command -v node >/dev/null 2>&1; then
    local cur
    cur="$(node -p 'process.versions.node' 2>/dev/null || echo "")"
    if [ -n "$cur" ] && node_engines_ok "$cur"; then
      NODE_BIN="$(command -v node)"
      NPM_BIN="$(command -v npm 2>/dev/null || echo npm)"
      log "using existing Node v$cur ($NODE_BIN)"
      return
    fi
    log "existing Node v${cur:-?} does not satisfy engines; bootstrapping Node $INSTALLER_NODE_VERSION"
  else
    log "no Node on PATH; bootstrapping Node $INSTALLER_NODE_VERSION"
  fi

  bootstrap_node
}

bootstrap_node() {
  local prefix="$NODE_PREFIX_BASE/$INSTALLER_NODE_VERSION"
  NODE_BIN="$prefix/bin/node"
  NPM_BIN="$prefix/bin/npm"
  # Record the bootstrapped Node bin dir so install_synapse_pkg persists it on
  # PATH too — a new shell's `synapse-device` shim (#!/usr/bin/env node) must
  # find this Node, not just the npm-global bin.
  BOOTSTRAPPED_NODE_BIN="$prefix/bin"

  # Idempotent: a healthy prior bootstrap is reused.
  if [ -x "$NODE_BIN" ] && [ "$("$NODE_BIN" -p 'process.versions.node' 2>/dev/null || echo)" = "$INSTALLER_NODE_VERSION" ]; then
    log "Node $INSTALLER_NODE_VERSION already bootstrapped at $prefix"
    activate_node "$prefix"
    return
  fi

  local expected
  expected="$(node_artifact_sha256 "$ARTIFACT_KEY")" \
    || die "no embedded sha256 for $ARTIFACT_KEY at Node $INSTALLER_NODE_VERSION"

  local file="node-v$INSTALLER_NODE_VERSION-$ARTIFACT_KEY.tar.gz"
  local tmp_dir tarball
  tmp_dir="$(mktemp -d -t synapse-node.XXXXXX)"
  track_tmp "$tmp_dir"
  tarball="$tmp_dir/$file"

  local base
  base="$(pick_reachable_mirror "$file")"
  log "downloading $file from ${base}"
  fetch_to_file "${base}v$INSTALLER_NODE_VERSION/$file" "$tarball"

  local got
  got="$(sha256_of "$tarball")"
  [ "$got" = "$expected" ] || die "Node sha256 mismatch for $file (expected $expected, got $got)"
  log "sha256 verified"

  run mkdir -p "$prefix"
  run tar -xzf "$tarball" -C "$prefix" --strip-components 1
  activate_node "$prefix"

  if [ "$DRY_RUN" != "true" ]; then
    [ -x "$NODE_BIN" ] || die "Node install incomplete: $NODE_BIN missing after extract"
  fi
}

# Probe the chosen mirror (and, for cn, cascade through the others) by GETting
# SHASUMS256.txt for our version — HEAD is unreliable across these CDNs.
pick_reachable_mirror() {
  local _file="$1" base
  local candidates="$NODE_MIRROR_BASE"
  if [ "$REGION" = "cn" ]; then
    candidates="$NODE_MIRROR_BASE https://mirrors.ustc.edu.cn/node/ https://mirrors.cloud.tencent.com/nodejs-release/ https://mirrors.huaweicloud.com/nodejs/ https://mirrors.aliyun.com/nodejs-release/ https://cdn.npmmirror.com/binaries/node/ https://nodejs.org/dist/"
  else
    candidates="$NODE_MIRROR_BASE https://nodejs.org/dist/"
  fi
  for base in $candidates; do
    if mirror_has_version "$base"; then printf '%s' "$base"; return; fi
    warn "mirror $base unreachable or missing v$INSTALLER_NODE_VERSION; trying next"
  done
  die "no reachable mirror for Node $INSTALLER_NODE_VERSION"
}

mirror_has_version() {
  local base="$1"
  command -v curl >/dev/null 2>&1 || { command -v wget >/dev/null 2>&1 || return 1; }
  if command -v curl >/dev/null 2>&1; then
    curl -fsS -m 8 --connect-timeout 3 -o /dev/null \
      "${base}v$INSTALLER_NODE_VERSION/SHASUMS256.txt" 2>/dev/null
  else
    wget -q -T 8 -O /dev/null "${base}v$INSTALLER_NODE_VERSION/SHASUMS256.txt" 2>/dev/null
  fi
}

activate_node() {
  # Put the bootstrapped Node + the managed npm-global bin on PATH for THIS
  # process and use absolute paths, so the freshly-installed npm shim
  # (#!/usr/bin/env node) resolves the new node.
  local prefix="$1"
  PATH="$prefix/bin:$NPM_GLOBAL_PREFIX/bin:$PATH"
  export PATH
}

# ---------------------------------------------------------------------------
fetch_to_file() {
  local url="$1" out="$2"
  # Pin curl to the URL's own scheme: https URLs stay https-only (a redirect
  # cannot downgrade them), while an http:// URL — the ps1 re-exec fetch from
  # an SYNAPSE_DEPLOY_MODE=http server — must be allowed at all ('=https'
  # refuses it outright). Third-party downloads (Node tarballs) are always
  # https URLs, so they keep the strict pin automatically.
  local proto='=https'
  case "$url" in
    http://*) proto='=http,https' ;;
  esac
  if command -v curl >/dev/null 2>&1; then
    run curl -fsSL --proto "$proto" --tlsv1.2 --retry 3 -o "$out" "$url" \
      || die "download failed: $url"
  elif command -v wget >/dev/null 2>&1; then
    run wget -q --tries=3 -O "$out" "$url" || die "download failed: $url"
  else
    die "neither curl nor wget available to download $url"
  fi
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die "no sha256 tool (sha256sum / shasum) available"
  fi
}

# ---------------------------------------------------------------------------
# Two distinct registries: third-party deps vs the @synapse private scope.
configure_npmrc() {
  [ -n "$PRIVATE_REGISTRY" ] || die "no private @synapse registry configured (PUBLIC_NPM_REGISTRY_URL empty); one-click bootstrap cannot install @synapse/*"

  THIRD_PARTY_REGISTRY=""
  if [ "$PREFER_PRIVATE_CACHE" = "true" ]; then
    THIRD_PARTY_REGISTRY="$PRIVATE_REGISTRY"   # route everything through Verdaccio cache
  elif [ "$REGION" = "cn" ]; then
    THIRD_PARTY_REGISTRY="${SYNAPSE_NPM_UPSTREAM_REGISTRY:-https://registry.npmmirror.com/}"
  else
    THIRD_PARTY_REGISTRY="${SYNAPSE_NPM_UPSTREAM_REGISTRY:-}"   # empty = npm default
  fi

  # Always write the managed npmrc (used via --userconfig, no global pollution).
  write_npmrc_file "$MANAGED_NPMRC"

  # --no-modify-path overrides --write-user-npmrc: never touch ~/.npmrc.
  if [ "$WRITE_USER_NPMRC" = "true" ] && [ "$NO_MODIFY_PATH" != "true" ]; then
    write_npmrc_file "$HOME/.npmrc"
  elif [ "$WRITE_USER_NPMRC" = "true" ] && [ "$NO_MODIFY_PATH" = "true" ]; then
    log "--no-modify-path set: skipping ~/.npmrc write; add manually:"
    log "  @synapse:registry=$PRIVATE_REGISTRY"
  fi
}

write_npmrc_file() {
  local path="$1"
  if [ "$DRY_RUN" = "true" ]; then
    echo "DRYRUN: write $path (@synapse:registry=$PRIVATE_REGISTRY; registry=${THIRD_PARTY_REGISTRY:-<default>})"
    return
  fi
  run mkdir -p "$(dirname "$path")"
  {
    echo "@synapse:registry=$PRIVATE_REGISTRY"
    if [ -n "$THIRD_PARTY_REGISTRY" ]; then
      echo "registry=$THIRD_PARTY_REGISTRY"
    fi
  } > "$path"
}

export_toolchain_mirror() {
  [ -n "$P5_MIRROR" ] || return 0
  export SYNAPSE_DEVICE_TOOLCHAIN_MIRROR="$P5_MIRROR"
  log "device toolchain mirror: $P5_MIRROR (this process)"
  if [ "$NO_MODIFY_PATH" = "true" ]; then
    log "--no-modify-path set: not persisting toolchain mirror; add manually:"
    log "  export SYNAPSE_DEVICE_TOOLCHAIN_MIRROR=$P5_MIRROR"
    return 0
  fi
  persist_env_line "export SYNAPSE_DEVICE_TOOLCHAIN_MIRROR=\"$P5_MIRROR\""
}

# ---------------------------------------------------------------------------
install_synapse_pkg() {
  local pkg bin
  case "$TARGET" in
    device) pkg="@synapse/device-runtime"; bin="synapse-device" ;;
    daemon) pkg="@synapse/remote-agent-daemon"; bin="synapse-remote-agent-daemon" ;;
  esac
  SYNAPSE_BIN="$NPM_GLOBAL_PREFIX/bin/$bin"

  # Pass each registry flag as its OWN quoted argv element — never via an
  # unquoted intermediate string. A registry value containing a space (e.g. a
  # malformed "url --@synapse:registry=evil") would otherwise word-split into
  # extra npm args and could override the private-scope pinning.
  local third_reg="${THIRD_PARTY_REGISTRY:-https://registry.npmjs.org/}"
  log "installing $pkg into $NPM_GLOBAL_PREFIX"
  run "$NPM_BIN" install --global --prefix "$NPM_GLOBAL_PREFIX" \
    --userconfig "$MANAGED_NPMRC" \
    "--registry=$third_reg" "--@synapse:registry=$PRIVATE_REGISTRY" "$pkg" \
    || die "npm install $pkg failed"

  # Persist the npm-global bin (where the synapse-* shims land) and, when we
  # bootstrapped our own Node, that Node's bin too — the shim's
  # `#!/usr/bin/env node` must resolve in a fresh shell.
  local path_dirs="$NPM_GLOBAL_PREFIX/bin"
  [ -n "$BOOTSTRAPPED_NODE_BIN" ] && path_dirs="$BOOTSTRAPPED_NODE_BIN:$path_dirs"
  if [ "$NO_MODIFY_PATH" = "true" ]; then
    log "--no-modify-path set: add this to your shell profile manually:"
    log "  export PATH=\"$path_dirs:\$PATH\""
  else
    persist_env_line "export PATH=\"$path_dirs:\$PATH\""
  fi
}

post_install() {
  case "$TARGET" in
    device) run_pair ;;
    daemon) run_daemon ;;
  esac
}

run_pair() {
  if [ -z "$PAIRING_CODE" ]; then
    log "device-runtime installed. To pair, run:"
    log "  \"$SYNAPSE_BIN\" pair --server \"${SERVER:-<server-url>}\" --code <pairing-code>"
    return
  fi
  [ -n "$SERVER" ] || die "--code given but --server missing; cannot auto-pair"
  log "pairing device..."
  if run "$SYNAPSE_BIN" pair --server "$SERVER" --code "$PAIRING_CODE"; then
    log "paired."
  else
    warn "auto-pair failed; run manually:"
    warn "  \"$SYNAPSE_BIN\" pair --server \"$SERVER\" --code \"$PAIRING_CODE\""
  fi
}

run_daemon() {
  if [ -z "$SERVER" ] || [ -z "$API_KEY" ]; then
    log "remote-agent-daemon installed. To start (foreground), run:"
    log "  \"$SYNAPSE_BIN\" --server-url \"${SERVER:-<server-url>}\" --api-key \"${API_KEY:-<api-key>}\""
    return
  fi
  log "starting remote-agent-daemon in this terminal session (foreground; Ctrl-C to stop)..."
  if ! run "$SYNAPSE_BIN" --server-url "$SERVER" --api-key "$API_KEY"; then
    warn "daemon exited / failed to start; run manually:"
    warn "  \"$SYNAPSE_BIN\" --server-url \"$SERVER\" --api-key \"$API_KEY\""
  fi
}

# ---------------------------------------------------------------------------
# Append a single guarded line to shell rc files, idempotently.
# Append a single guarded line to shell rc files, idempotently. If NONE of the
# usual rc files exist (fresh HOME / minimal image), create ~/.profile so the
# line actually lands somewhere. Always print the line so the user can apply it
# to the current shell immediately.
persist_env_line() {
  local line="$1" rc wrote=false
  local rcs="$HOME/.profile $HOME/.bashrc $HOME/.zshrc"
  for rc in $rcs; do
    [ -e "$rc" ] || continue
    wrote=true
    if grep -Fq "$line" "$rc" 2>/dev/null; then continue; fi
    if [ "$DRY_RUN" = "true" ]; then
      echo "DRYRUN: append to $rc: $line"
      continue
    fi
    {
      echo ""
      echo "$RC_MARKER_BEGIN"
      echo "$line"
      echo "$RC_MARKER_END"
    } >> "$rc"
    log "updated $rc (open a new shell or 'source $rc')"
  done
  if [ "$wrote" = "false" ]; then
    # No rc file existed — create ~/.profile so the change persists.
    if [ "$DRY_RUN" = "true" ]; then
      echo "DRYRUN: create $HOME/.profile with: $line"
    else
      {
        echo "$RC_MARKER_BEGIN"
        echo "$line"
        echo "$RC_MARKER_END"
      } >> "$HOME/.profile"
      log "created $HOME/.profile (open a new shell or 'source ~/.profile')"
    fi
  fi
  log "to use it now: $line"
}

__main "$@"
